site_name: Your Serverless Wiki
site_url: https://danieldreke.github.io/serverless-wiki/
repo_url: https://github.com/danieldreke/serverless-wiki/wiki
edit_uri: ./_edit
hooks:
  - change_edit_url.py
plugins:
  - search
theme:
  name: material
  features:
    - content.action.edit
  user_color_mode_toggle: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
